[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rwa_tokenization = "RWA1111111111111111111111111111111111111111"

[programs.devnet]
rwa_tokenization = "RWA1111111111111111111111111111111111111111"

[programs.mainnet]
rwa_tokenization = "RWA1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/rwa-tokenization.ts"

[test]
startup_wait = 3000
shutdown_wait = 2000
upgradeable = false

